# Generated by Django 3.2.6 on 2021-08-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('status', models.BooleanField(default=True, help_text='Toggle the status.', verbose_name='active')),
                ('name', models.CharField(error_messages={'blank': 'Please enter the valid name.'}, help_text='Enter the category name.', max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'db_table': 'cateory',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('status', models.BooleanField(default=True, help_text='Toggle the status.', verbose_name='active')),
                ('name', models.CharField(error_messages={'blank': 'Please enter the valid product name.'}, help_text='Enter the product name.', max_length=50, verbose_name='Name')),
                ('notes', models.TextField(error_messages={'blank': 'Enter the valid description.'}, help_text='Enter the description.', verbose_name='Description')),
                ('category', models.ForeignKey(help_text='Choose the category.', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='cateory_name_b01cff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_c4c985_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_categor_26b384_idx'),
        ),
    ]
