# Generated by Django 3.2.6 on 2021-08-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('status', models.BooleanField(default=True, help_text='Toggle the status of the user.')),
                ('email', models.EmailField(help_text='Email of user', max_length=254, unique=True)),
                ('username', models.CharField(help_text='Enter your username.', max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, default='', help_text='First Name of user', max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, default='', help_text='Name Name of user', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggles active status for a user.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates the user as a staff member.')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates the user as a super user.')),
                ('is_verified', models.BooleanField(default=False, help_text='Toggles verification status for a user.')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='user_is_acti_7f3bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff'], name='user_is_staf_3c0a45_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='user_is_veri_176129_idx'),
        ),
    ]
