# Generated by Django 3.2.6 on 2021-08-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210823_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True, help_text='Toggle the status.', verbose_name='active'),
        ),
    ]
