# Generated by Django 3.2.6 on 2021-08-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
